#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

#Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_clean_setup () {
    ### Remove this function if there's nothing to clean before calling the remove script.
    true
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================
ynh_print_info "Loading installation settings..."

app=$YNH_APP_INSTANCE_NAME

final_path=$(ynh_app_setting_get --app=$app --key=final_path)
domain=$(ynh_app_setting_get --app=$app --key=domain)

backup_dir=$1

path=$(ynh_app_setting_get --app=$app --key=path)
final_path=$(ynh_app_setting_get --app=$app --key=final_path)

my_ynh_backup () {
    ynh_backup $@
    echo $2 $1 >> $backup_dir/list
}

# Copy the app files
my_ynh_backup "$final_path" "sources"
my_ynh_backup "/etc/openvpn" "etc"
my_ynh_backup "/etc/yunohost/certs/${domain}/dh.pem" "certs/dh.pem"

# Copy the conf files
my_ynh_backup "/etc/sysctl.d/openvpn.conf" "conf/sysctl"
my_ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf" "conf/nginx.conf"
my_ynh_backup "/etc/php/7.0/fpm/pool.d/$app.conf" "conf/php-fpm.conf"
my_ynh_backup "/etc/fail2ban/jail.d/${app}.conf" "conf/f2b_jail.conf"
my_ynh_backup "/etc/fail2ban/filter.d/$app.conf" "conf/f2b_filter.conf"

# Copy log
my_ynh_backup "/var/log/openvpn" "log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
