#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers
source _common.sh

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

ynh_print_info "Loading installation settings..."

app=$YNH_APP_INSTANCE_NAME
user=$app
webuser="${user}web"

final_path="/var/www/$app"
domain=$(ynh_app_setting_get $app domain)
port=$(ynh_app_setting_get $app port)

#=================================================
# STOP AND REMOVE SERVICES
#=================================================

ynh_print_info "Stopping and removing services"

service $service_name stop
yunohost service remove $service_name

#=================================================
# STOP AND REMOVE FIREWALL RULES
#=================================================

ynh_print_info "Stopping and removing firewall rules"

yunohost firewall disallow UDP $port > /dev/null 2>&1
rm_firewall_rules

#=================================================
# SPECIFIC REMOVE
#=================================================

ynh_print_info "Removing openvpn configuration"

# === sysctl

sysctl net.ipv4.ip_forward=0

# === config

# We don't delete all /etc/openvpn because it could be used by vpnclient_ynh
ynh_secure_remove /etc/openvpn/server.conf
ynh_secure_remove /etc/openvpn/auth
ynh_secure_remove /etc/openvpn/ta.key
ynh_secure_remove /etc/openvpn/users
ynh_secure_remove /etc/openvpn/handler.sh
ynh_secure_remove /etc/openvpn/ip4_attribution.csv
ynh_secure_remove "/etc/sysctl.d/$service_name.conf"

# TODO: May be we shouldn't remove it
ynh_secure_remove /var/log/openvpn

ynh_secure_remove "$final_path"
ynh_secure_remove "/etc/yunohost/certs/${domain}/dh.pem"

#=================================================
# REMOVE DEPENDENCIES
#=================================================

ynh_print_info "Removing dependencies..."

# Remove metapackage and its dependencies
ynh_remove_app_dependencies

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================

ynh_print_info "Removing nginx web server configuration"

# Remove the dedicated nginx config
ynh_remove_nginx_config

#=================================================
# REMOVE PHP-FPM CONFIGURATION
#=================================================

ynh_print_info "Removing php-fpm configuration"

# Remove the dedicated php-fpm config
ynh_remove_fpm_config

#=================================================
# REMOVE DEDICATED USER
#=================================================

ynh_print_info "Removing the dedicated system user"

ynh_system_user_delete "$user"
ynh_system_user_delete "$webuser"

ynh_secure_remove "/etc/sudoers.d/${app}_ynh"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Removal of $app completed"
