#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers
source ../settings/scripts/_common.sh

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================
ynh_print_info "Loading settings..."

app=$YNH_APP_INSTANCE_NAME
user=$app
webuser="${user}web"

domain=$(ynh_app_setting_get $app domain)
path_url=$(ynh_app_setting_get $app path)
final_path=$(ynh_app_setting_get $app final_path)
iface=$(ynh_app_setting_get $app iface)
port=$(ynh_app_setting_get $app port)
ip4ranges=$(ynh_app_setting_get $app ip4ranges)
dynamic_ip=$(ynh_app_setting_get $app dynamic_ip)
dedicated_ip=$(ynh_app_setting_get $app dedicated_ip)

#=================================================
# CHECK IF THE APP CAN BE RESTORED
#=================================================
ynh_print_info "Validating restoration parameters..."

ynh_webpath_available $domain $path_url \
    || ynh_die "Path not available: ${domain}${path_url}"
    test ! -d $final_path \
    || ynh_die "There is already a directory: $final_path "

check_iptables
check_tun_available

#=================================================
# RESTORE THE APP BY MODIFYING THE SYSTEM
#=================================================

#=================================================
# REINSTALL DEPENDENCIES
#=================================================

ynh_print_info "Reinstalling dependencies..."

# Define and install dependencies
ynh_install_app_dependencies "$pkg_dependencies"

install_files () {
    ynh_restore
}

setup_and_restart

#=================================================
# GENERIC FINALIZATION
#=================================================
# RELOAD NGINX AND PHP-FPM
#=================================================

ynh_print_info "Setting Nginx and php-fpm..."

ynh_systemd_action --service_name=php7.0-fpm --action=reload
ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Restoration completed for $app"
