#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers
source _common.sh

#=================================================
# LOAD SETTINGS
#=================================================
ynh_print_info "Loading installation settings..."

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
path_url=$(ynh_app_setting_get $app path)

user=$app
webuser="${user}web"

export domain=$(ynh_app_setting_get $app domain)
domain=${prefix:-$(cat /etc/yunohost/current_host)}
export path=$(ynh_app_setting_get $app path)
path=${path:-/openvpn/}
export final_path=$(ynh_app_setting_get $app final_path)
final_path=${final_path:-/var/www/$app}
export iface=$(ynh_app_setting_get $app iface)
iface=${iface:-$(ip r|awk '/default/ { print $5 }')}
export port=$(ynh_app_setting_get $app port)
port=${port:-1194}
export ip4ranges=$(ynh_app_setting_get $app ip4ranges)
ip4ranges=${ip4ranges:-10.0.0.8/24}
export dynamic_ip=$(ynh_app_setting_get $app dynamic_ip)
dynamic_ip=${dynamic_ip:-false}


version=$(ynh_read_json "/etc/yunohost/apps/$app/manifest.json" 'version' 2> /dev/null || echo '2.3.4-1')
last_version=$(ynh_read_manifest 'version')

ynh_exit_if_up_to_date
ynh_check_var "$app" "app name not set"
ynh_normalize_url_path "$path"

if [ "${version}" = "2.3.4-1" ]; then
    ynh_save_args domain path ip4ranges port final_path iface dynamic_ip

    # Install official debian package
    ynh_app_dependencies openvpn,openvpn-auth-ldap,netmask

    # Delete old cron (replace by a iptables hooks)
    rm -f /etc/openvpn/yunohost.cron

    # Install configured files and restart services
    setup_and_restart

    mv /var/log/openvpn.log /var/log/openvpn/status.log
fi

if [ "${version}" = "2.3.4-2" ]; then
    touch /etc/openvpn/crl.pem
    mkdir -p /etc/openvpn/users
    touch /etc/openvpn/ip4_attribution.csv
    cp ../conf/handler.sh /etc/openvpn/handler.sh
    chown -R $user: /etc/openvpn
    chmod 640 /etc/openvpn/ip4_attribution.csv
    chmod u+x /etc/openvpn/handler.sh
fi

#=================================================
# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
#=================================================

ynh_print_info "Backing up the app before upgrading (may take a while)..."

# Backup the current version of the app

ynh_backup_before_upgrade
ynh_clean_setup () {
    # restore it if the upgrade fails
    ynh_restore_upgradebackup
}

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# UPGRADE DEPENDENCIES
#=================================================

ynh_print_info "Upgrading dependencies..."

ynh_install_app_dependencies $pkg_dependencies

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Upgrade of $app completed"
